version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: billiard_app
    volumes:
      - .:/app

  db:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billiard_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
